# Support ES2016 features
extends: airbnb-base

plugins: ["babel"]

parser: babel-eslint

parserOptions:
  sourceType: module

rules:
  strict: 0
  arrow-parens: 0
  no-console: 0
  spaced-comment: [2, "always", { exceptions: ["-"]}]
  eqeqeq: 0
  no-return-assign: 0 # fails for arrow functions
  no-var: 2
  semi: [2, never]
  space-before-function-paren: [2, "never"]
  yoda: 0
  arrow-spacing: 2
  dot-location: [2, "property"]
  keyword-spacing: [2, { after: true, before: true }]
  indent: [2, 2]
  camelcase: 0
  key-spacing: [1, { beforeColon: false, afterColon: true, mode: "minimum" }]
  space-in-parens: [1, "never"]
  no-param-reassign: 0
  no-unused-vars: [1, {"vars": "local", "args": "none"}]
  new-cap: [0, {"capIsNewExceptions": ["Immutable.Map", "Immutable.Set", "Immutable.List"]}]
  no-underscore-dangle: 0
  no-use-before-define: 0
  prefer-arrow-callback: [1, { allowNamedFunctions: true}]
  space-before-blocks: 0
  max-len: 0
  no-plusplus: 0
  generator-star-spacing: 0
  babel/new-cap: 0
  array-bracket-spacing: 1
  babel/object-curly-spacing: 0
  object-shorthand: 1
  babel/no-await-in-loop: 1
  babel/func-params-comma-dangle: 0
  import/imports-first: 0
  class-methods-use-this: 0
  react/require-extension: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  guard-for-in: 0
  consistent-return: 0
  arrow-body-style: 0
